apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-node
  labels:
    name: redis-node
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: redis-node
    spec:
        containers:
        - image: redis:3.2
          name: redis-node
          ports:
          - containerPort: 6379
