apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: scrumblr-dep
  labels:
    name: scrumblr-dep
spec:
  template:
    metadata:
      labels:
        name: scrumblr-dep
    spec:
      containers:
      - image: asia.gcr.io/${PROJECT_ID}/scrumblr:v1.10
        name: scrumblr-node
        ports:
        - containerPort: 8080
      - image: asia.gcr.io/${PROJECT_ID}/scrumblr-nginx:v1.2
        name: nginx-node
        ports:
        - containerPort: 80
      - image: redis:3.2
        name: redis-node
        ports:
        - containerPort: 6379
        volumeMounts:
        - mountPath: /data
          name: redis-volume
      volumes:
      - name: redis-volume
        gcePersistentDisk:
          pdName: scrumblr-disk
          fsType: ext4
