apiVersion: v1
kind: Service
metadata:
  name: scrumblr-svc
  labels:
    name: scrumblr-svc
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    name: scrumblr-dep
  type: LoadBalancer
